version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped 